title: "Wini"
tagline: "Blogs like a shell/terminal"
description: "This is Wini's blog."
github_username: XindanZhang
baseurl: "/myblog"
url: "https://XindanZhang.github.io"

permalink: /:year/:month/:day/:title/

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - blog.md
  - aboutme.md


# set the size of the text to 'large' or 'small', default is small
font-size: small

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge